language: php
php:
  - '5.6'

install:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install
  - php init --env=Test
  - tests/bin/yii  migrate/up --migrationPath=modules\lectors\migrations --interactive=0
  - vendor\codeception\codeception\codecept build

script: vendor/codeception/codeception/codecept run unit,functional
