language: php
php:
  - '5.6'

install:
  - composer install
  - init --env=Test
  - tests\bin\yii  migrate/up --migrationPath=modules\lectors\migrations --interactive=0
  - vendor\codeception\codeception\codecept build

script: vendor\codeception\codeception\codecept run unit,functional
